name: Deploy to EKS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      cluster: "eks-mundos-e2"
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
        with:
           version: 'v1.23.6' # default is latest stable
        id: install 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  
      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ env.cluster }} --region us-east-1
      - name: Deploy to EKS
        run: |
          kubectl apply -f nginx-deploy.yaml
